### ISSUE TITLE
only can you share data? to try your code?

### ISSUE THREAD

**Issue by Sandy4321** [daydayupPro/KDDCup2020_AutoGraph#1]
great code thanks
only can you share data? to try your code?

**Comment by daydayupPro** [comment]
All the data format like `data/demo` is supported. And you can download five public datasets from website [AutoML](https://automl.ai/competitions/3#learn_the_details)

**Comment by Sandy4321** [comment]
https://automl.ai/competitions/3#learn_the_details

Data is unavailable

Can you just share data
